### ISSUE TITLE
[BUG] bots with 1.17 citizens are broken

### ISSUE THREAD

**Issue by toppev** [toppev/strikepractice-public#5]
**Describe the bug**
Bots don't work on latest citizens 1.17
I need to test this stuff when I have time

Some error
`[10:37:01 WARN]: [StrikePractice] Task #1317826 for StrikePractice v3.4.4-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'void net.citizensnpcs.util.Util.assumePose(org.bukkit.entity.Entity, float, float)'
        at ga.strikepractice.npc.d.g(CombatTask.java:214) ~[strikepractice-3.4.4.jar:?]`

(this issue is just for myself, don't even think of making this bad issues)

**Comment by iiAhmedYT** [comment]
isn't this already fixed?
